language: python
python:
 - "3.6"

env:
  - PYTHONPATH=`pwd`

install:
  - pip install pytest pytest-django
  - pip install -r requirements.txt

script: DJANGO_SETTINGS_MODULE=test_settings pytest wistiavideo
